// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://puzghxziqjxcecstinxw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB1emdoeHppcWp4Y2Vjc3Rpbnh3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5NzE4ODEsImV4cCI6MjA3MzU0Nzg4MX0.Ah3yiY4dbVuu700nSn0t-TZ1I3dxyNl6LLHXb2USuyM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});